# Generated by Django 5.1.1 on 2024-10-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='isim',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='soyisim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
