# Generated by Django 5.1.1 on 2024-10-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('soyisim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon_numarasi', models.CharField(max_length=15)),
                ('urun_adi', models.CharField(max_length=100)),
                ('urun_markasi', models.CharField(max_length=100)),
                ('urun_ebadi', models.CharField(max_length=50)),
                ('urun_tipi', models.CharField(max_length=50)),
                ('adet', models.IntegerField(default=1)),
                ('depo_bilgisi', models.CharField(max_length=100)),
                ('firma_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('not_bilgisi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Musteri',
        ),
    ]
