# Generated by Django 5.1.1 on 2024-10-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0002_customer_delete_musteri'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=100, null=True)),
                ('soyisim', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_adi', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefon_numarasi', models.CharField(max_length=10)),
                ('arac_plakasi', models.CharField(blank=True, max_length=20, null=True)),
                ('urun_adi', models.CharField(max_length=100)),
                ('urun_markasi', models.CharField(max_length=100)),
                ('urun_ebadi', models.CharField(max_length=50)),
                ('urun_tipi', models.CharField(choices=[('Yazlık', 'Yazlık'), ('Kışlık', 'Kışlık'), ('Dört Mevsim', 'Dört Mevsim')], max_length=50)),
                ('adet', models.PositiveIntegerField()),
                ('depo_bilgisi', models.CharField(max_length=100)),
                ('not_field', models.TextField(blank=True, null=True)),
                ('raf_numarasi', models.CharField(max_length=20, unique=True)),
                ('durum', models.CharField(default='Aktif', max_length=50)),
                ('ikinci_urun_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('ikinci_urun_markasi', models.CharField(blank=True, max_length=100, null=True)),
                ('ikinci_urun_ebadi', models.CharField(blank=True, max_length=50, null=True)),
                ('ikinci_urun_adet', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
