# Generated by Django 5.1.1 on 2024-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0003_musterikayit_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musterikayit',
            name='raf_numarasi',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
