# Generated by Django 5.1.1 on 2024-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0004_alter_musterikayit_raf_numarasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musterikayit',
            name='raf_numarasi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
