# Generated by Django 5.1.1 on 2024-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0007_alter_musterikayit_raf_numarasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musterikayit',
            name='raf_numarasi',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
